# The NEW default config
LEFT_PIXEL_X: 709
LEFT_PIXEL_Y: 840

RIGHT_PIXEL_X: 1216
RIGHT_PIXEL_Y: 840

DEBOUNCE_DELAY: 0.043

# For determining when to curve swipe
VERY_FAST_THRESHOLD: 0.8

y_middle: 410
duration: 100
faster_h_duration: 180
faster_v_duration: 170
factor: 10000
h_move_iteration: 500
v_move_iteration: 500


# Determine whether horizontal swipes are "true" horizontal swipes
# 0: False 1: True 
left_h_move_true: 1
right_h_move_true: 1

# y_bias is only affected on the horizontal swipes that are 'true' horizontal (value above is set to 1)
# 0 = no bias, 1 = upper bias, 2: lower bias... 
y_bias: 2

# Note that if it's not 1,1,2 then maximum flowiness is not guarenteed....