# Slow Config
# But it's actually pretty good and can do GHOST 1,2x
LEFT_PIXEL_X: 709
LEFT_PIXEL_Y: 840

RIGHT_PIXEL_X: 1216
RIGHT_PIXEL_Y: 840

DEBOUNCE_DELAY: 0.0425

y_middle: 410
duration: 120
faster_h_duration: 180
faster_v_duration: 170
factor: 10000
h_move_iteration: 500
v_move_iteration: 500


# Determine whether horizontal swipes are "true" horizontal swipes
# 0: False 1: True 
left_h_move_true: 0
right_h_move_true: 1